name: elm2d-crabnet
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython #ElM2D
  - numba #ElM2D
  - python=3.8.*
  - numpy
  - scipy #ElM2D
  - pandas
  - scikit-learn
  - plotly #ElM2D
  - setuptools #ElMD
  - umap-learn #ElM2D
  - matplotlib
  - seaborn
  - pytorch=1.7.*
  - cudatoolkit=11.*
  - tqdm
