{% set name = "crabnet" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crabnet-{{ version }}.tar.gz
  sha256: c753ca524d1304ce399ca4c992c684636acccf9739400758bbd547630bf89e29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.6,<3.10
  run:
    - joblib
    - cudatoolkit ==11.3.1
    - pytorch >=1.9.0
    - matplotlib-base
    - numpy
    - pandas
    - psutil
    - python >=3.6,<3.10
    - scikit-learn
    - scipy
    - seaborn
    - tqdm

test:
  imports:
    - crabnet
    - crabnet.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/crabnet/
  summary: Predict materials properties using only the composition information.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
