name: Build with Miniconda and test

on:
  push:
    paths:
    - '**.py'
#     - 'pyproject.toml'
#       - '!**/*.md'
    branches:
    - "**"
    tags-ignore:
    - "*.*.*"
  workflow_dispatch:

jobs:
  linux-pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      
    - uses: psf/black@stable #https://black.readthedocs.io/en/stable/integrations/github_actions.html
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: crabnet
    
    - name: Install dependencies
      run: |
        conda install git conda-build conda-verify anaconda-client pytest
        conda install  -c conda-forge flit grayskull
        
    - name: Miniconda build
      run : |
        mkdir scratch
        cp LICENSE scratch/
        python run_grayskull.py
        conda config --append channels conda-forge
        conda config --append channels sgbaird
        conda config --set anaconda_upload no
        cd scratch
        conda build .
        cd ..
        conda install --use-local crabnet
    
    - name: Pytest
      run: |
        python -m pytest
