name: Dependabot CI
on:
  pull_request:
    paths:
      - "**/requirements.txt"
      
jobs:
  dependabot:
    runs-on: ubuntu-latest
#     if: ${{ github.actor == 'dependabot[bot]' }}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Upgrade pip
      shell: bash {0}
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      shell: bash {0}
      run: |
        pip install flit torch pytest
        pip install -r requirements.txt
        flit install
    - name: Test with pytest
      shell: bash {0}
      run: |
        export NUMBA_ENABLE_CUDASIM="1"
        python -m pytest
