name: Manual Code Coverage

on: workflow_dispatch

jobs:
  linux-pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install flit torch coveralls pytest # torch is CPU version
        flit install
        
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export NUMBA_ENABLE_CUDASIM="1"
        coverage run --source=crabnet -m pytest
        
    - name: Upload to coveralls
      shell: bash -l {0}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
